# Generated by Django 5.1.7 on 2025-03-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_capybara', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Ваша фамилия'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Телеграм ник'),
        ),
    ]
