# Generated by Django 5.1.7 on 2025-03-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('new_users', models.IntegerField(default=0)),
                ('new_products', models.IntegerField(default=0)),
                ('product_views', models.IntegerField(default=0)),
                ('favorites_added', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cтатистика',
                'verbose_name_plural': 'Cтатистика',
                'ordering': ['-date'],
            },
        ),
    ]
