# Generated by Django 5.1.7 on 2025-05-24 02:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='app_categor_slug_0ace88_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['order'], name='app_categor_order_afbaac_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user'], name='app_favorit_user_id_93dc7a_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['product'], name='app_favorit_product_da414f_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['created_at'], name='app_favorit_created_955937_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product'], name='app_product_product_a532da_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['user'], name='app_product_user_id_7b6768_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['ip_address'], name='app_product_ip_addr_0e3365_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['created_at'], name='app_product_created_1285e4_idx'),
        ),
    ]
